export const MICROSERVICE_DOMAINS = {
    INVENTORY: process.env.INVENTORY_MICROSERVICE_DOMAIN,
    ORDERS: process.env.ORDERS_MICROSERVICE_DOMAIN,
    CUSTOMERS: process.env.CUSTOMERS_MICROSERVICE_DOMAIN,
  }
  